spring.application.name=azentrix-fullstack-task2

spring.datasource.url=jdbc:postgresql://localhost:5432/notesdb
spring.datasource.username=postgres
spring.datasource.password=2200032487

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081